# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datamodule: mimic_cxr.yaml
  - model: convirt_resnet_model.yaml
  - callbacks: convirt_pretrain_callbacks.yaml
  - logger: wandb # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: convirt_pretrain_trainer.yaml
  - paths: convirt_pretrain_paths.yaml
  - hydra: default.yaml
  - extras: default.yaml
  - debug: null # debugging config (enable through command line, e.g. `python train.py debug=default)

# task name, determines output directory path
task_name: "convirt_pretrain"

# set False to skip model training
train: True

# dimensions of the projection layer
proj_dim_size: 512

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: False

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 42

tags: ['dev']