defaults:
  - _self_
  - paths: visualization_paths.yaml
  - model: visualization_model.yaml
  - hydra: default.yaml
  - extras: default.yaml
  - debug: null

task_name: "feature_visualization"

transform:
  # Default transformations from the ConVIRT paper
  - _target_: torchvision.transforms.ToTensor # Convert PIL Image to tensor since normalization requires tensor input
  - _target_: torchvision.transforms.RandomResizedCrop
    size: 224
    ratio: [0.6, 1.0]
  - _target_: torchvision.transforms.RandomAffine
    degrees: [-20, 20]
    translate: [0.1, 0.1]
    scale: [0.95, 1.05]
  - _target_: torchvision.transforms.ColorJitter
    contrast: [0.6, 1.4]
    brightness: [0.6, 1.4]
  - _target_: torchvision.transforms.GaussianBlur
    kernel_size: 3
    sigma: [0.1, 3.0]
  - _target_: torchvision.transforms.RandomHorizontalFlip
    p: 0.5
  - _target_: torchvision.transforms.Resize
    size: [224, 224]
  - _target_: torchvision.transforms.Normalize
    mean: [0.398, 0.398, 0.398]
    std: [0.327, 0.327, 0.327]

# t-SNE parameters
tsne:
  n_components: 2
  perplexity: 30
  n_iter: 1000
  learning_rate: 200
  random_state: 42

# UMAP parameters
umap:
  n_components: 2
  n_neighbors: 15
  min_dist: 0.1
  random_state: 42

subset_size: None
mapping: "tsne"

seed: 42