_target_: src.datamodules.nlmcxr_datamodule.NLMCXRDataModule
batch_size: 32
num_workers: 16
pin_memory: True
text_model_name: 'emilyalsentzer/Bio_ClinicalBERT'
nlmcxr_dataset_file: '/vol/miltank/projects/practical_WS2425/vision_language/data/interims/nlmcxr_preprocessed_tokenized_sentences.pkl'
train_val_split: [0.9775,0.0225]
seed: ${seed}